project:
  type: website
  output-dir: _site

website:
  title: "AL-OTHMAN"
  description: "Abdulwahab Al-Othman. Political science, Georgia State University. Research on how conspiratorial claims acquire political authority."
  navbar:
    left:
      - href: index.qmd
        text: Index
      - href: research/index.qmd
        text: Research
      - href: notes/index.qmd
        text: Log
      - href: site/cv.qmd
        text: Record
  page-navigation: true
  page-footer:
    left: "A. AL-OTHMAN &nbsp;//&nbsp; DEPT. OF POLITICAL SCIENCE &nbsp;//&nbsp; GEORGIA STATE UNIVERSITY"
    right: "LAST REVISION 2026-09-11"

format:
  html:
    theme: [darkly, site/custom.scss]
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    anchor-sections: false
    link-external-newwindow: true
    code-fold: true
