project:
  type: website
  output-dir: _site

website:
  title: "AL-OTHMAN"
  navbar:
    left:
      - href: index.qmd
        text: Index
      - href: research/index.qmd
        text: Research
      - href: notes/index.qmd
        text: Log
      - href: site/cv.qmd
        text: Record
  page-footer:
    left: "A. AL-OTHMAN &nbsp;·&nbsp; العثمان"
    right: "2026"

format:
  html:
    theme: [darkly, site/custom.scss]
    toc: true
    toc-depth: 2
    toc-title: "Contents"
    anchor-sections: false
    code-fold: true
